name: Run test on PR

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted

    permissions:
      id-token: write
      contents: read
      checks: write

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: "8.0.x"

      - name: Write .env file
        run: echo "${{ secrets.ENV }}" > CoursesManager.UI/.env

      - name: Run unit tests
        env:
          ReportPortal__server__authentication__uuid: ${{ secrets.RP_UUID }}
        run: dotnet test --logger "trx;LogFileName=TestResults.trx"

      - name: Upload test results
        uses: dorny/test-reporter@v1
        if: success() || failure()
        with:
          name: TestResults
          path: "**/TestResults.trx"
          reporter: dotnet-trx
          fail-on-error: true
